config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :friends, only: [:index, :show] do
    resources :bookings, only: [:index, :new, :create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :bookings, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :friend
end

app/models/friend.rb
class Friend < ApplicationRecord
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @friend = Friend.find(params[:friend_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @friend = Friend.find(params[:friend_id])
    @booking[:user_id] = current_user.id
    @booking[:friend_id] = @friend.id
    if @booking.save
      redirect_to friend_bookings_path(@friend)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to friends_path
  end

  private

  def booking_params
    params.require(:booking).permit(:time, :date, :location, :user_id, :friend_id)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = Friend.all
  end

  def show
    @friend = Friend.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>My Bookings</h1>
<% @bookings.each do |booking| %>
<div class="card">
  <h3><%= link_to booking.friend.name, booking_path(booking.id) %></h3>
  <p><%= booking.date %></p>
  <p><%= booking.time %></p>
  <p><%= booking.location %></p>
</div>
<% end %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<%= simple_form_for [@friend, @booking] do |f| %>
<%= f.input :location %>
<%= f.input :date %>
<%= f.input :time %>
<%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Show</h1>
<p><%= @booking.friend.name %></p>
<p><%= @booking.date %></p>
<p><%= @booking.time %></p>
<p><%= @booking.location %></p>
<%= link_to "Delete this booking", booking_path(@booking.id), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/friends/index.html.erb
<h1>Friends Index</h1>
<% @friends.each do |friend| %>
<div class="card">
  <p><%= link_to friend.name, friend_path(friend.id) %></p>
  <p><%= friend.location %></p>
  <p><%= friend.interest %></p>
  <p>£<%= friend.price %></p>
  <p><%= friend.bio %></p>
</div>
<% end %>

app/views/friends/show.html.erb
<h1><%= @friend.name %></h1>
<p><%= @friend.location %></p>
<p><%= @friend.interest %></p>
<p>£<%= @friend.price %></p>
<p><%= @friend.bio %></p>
<%= link_to "Book me", new_friend_booking_path(@friend.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAFriend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "My Profile", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "My Bookings", friend_bookings_path(current_user), class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1><%=  @user.name %>'s Profile</h1>